### ISSUE TITLE
Server Timeout with .git files

### ISSUE THREAD

**Issue by Dylienne** [IDLabResearch/Git2PROV#13]
The server often times out when i try to upload certain .git files to prov-json.
It gives error: 504

**Comment by tdn** [comment]
Does this happen when you run the server locally, or on the public demo?

On the public server, this is a safety measure to make sure really big repositories don't get dumped on our server. Locally, you can tweak this on line 36 of https://github.com/IDLabResearch/Git2PROV/blob/master/lib/git2provConverter.js

**Comment by Dylienne** [comment]
The time-out happens with the Demo. Some files work and some just dont. 
Seen your answer, I think the files are in a way too large. 
Any tips?

**Comment by tdn** [comment]
Yes, install locally and apply the fix I put in the previous comment. 
The online demo is for demonstration purposes only, and isn't meant to handle large files. 

It'll be much more robust if you install it locally and adjust the timeout to what you need.
